### ISSUE TITLE
 Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/mobi-com-kit#102]
07-29 02:04:27.559    1894-1894/com.mobicomkit.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mobicomkit.sample, PID: 1894
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
            at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:154)
            at android.app.AlertDialog$Builder.<init>(AlertDialog.java:379)
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.deleteConversationThread(MobiComConversationFragment.java:848)
            at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.onOptionsItemSelected(ConversationActivity.java:154)
            at android.app.Activity.onMenuItemSelected(Activity.java:2882)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:350)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
            at android.support.v7.app.ActionBarActivityDelegate$1.onMenuItemSelected(ActionBarActivityDelegate.java:74)
            at android.support.v7.app.ActionBarActivityDelegateBase.onMenuItemSelected(ActionBarActivityDelegateBase.java:556)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
            at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:187)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
            at android.widget.AbsListView$3.run(AbsListView.java:3833)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
07-29 02:04:30.335    2344-2361/com.mobicomkit.sample D/OpenGLRenderer﹕ Render dirty regions requested: true
07-29 02:04:30.338    2344-2344/com.mobicomkit.sample D/﹕ HostConnection::get() New Host Connection established 0xa6ccd090, tid 2344
07-29 02:04:30.485    2344-2344/com.mobicomkit.sample D/Atlas﹕ Validating map...
07-29 02:04:30.555    2344-2361/com.mobicomkit.sample D/﹕ HostConnection::get() New Host Connection established 0xa6ccd350, tid 2361
07-29 02:04:30.581    2344-2361/com.mobicomkit.sample I/OpenGLRenderer﹕ Initialized EGL, version 1.4
07-29 02:04:30.602    2344-2361/com.mobicomkit.sample D/OpenGLRenderer﹕ Enabling debug mode 0
07-29 02:04:30.652    2344-2361/com.mobicomk

**Comment by DoveBarnett** [comment]
这个问题是怎么产生的？又怎么解决的呢？或者怎么做会使之不再发生？
