### ISSUE TITLE
New contact-list fragment for sample app

### ISSUE THREAD

**Issue by adarshmishra** [AppLozic/mobi-com-kit#105]

**Comment by devashishmamgain** [comment]
@adarshmishra  App is crashing on click of plus button
.211  24227-24227/com.mobicomkit.sample D/AndroidRuntime﹕ Shutting down VM
08-02 13:46:56.213  24227-24227/com.mobicomkit.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mobicomkit.sample, PID: 24227
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mobicomkit.sample/com.applozic.mobicomkit.uiwidgets.people.activity.MobiComKitPeopleActivity}: java.lang.ClassCastException: com.applozic.mobicomkit.uiwidgets.contacts.fragment.AppContactFragment cannot be cast to com.applozic.mobicomkit.uiwidgets.people.fragment.ContactsListFragment
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassCastException: com.applozic.mobicomkit.uiwidgets.contacts.fragment.AppContactFragment cannot be cast to com.applozic.mobicomkit.uiwidgets.people.fragment.ContactsListFragment
            at com.applozic.mobicomkit.uiwidgets.people.activity.MobiComKitPeopleActivity.onCreate(MobiComKitPeopleActivity.java:54)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
