### ISSUE TITLE
Messaging interface using fragments

### ISSUE THREAD

**Issue by Sunilkumarr** [AppLozic/mobi-com-kit#65]

**Comment by devashishmamgain** [comment]
@Sunilkumarr 
1. Title is not coming in the individual conversation thread, it is showing "Conversations". Open app, click on "Chat", now it shows "Conversations", title should be the name of the contact or the userId.

2. Delete single message is crashing app with the following error in case if the message is the last one in the list.
07-05 13:26:44.840  31899-31899/com.mobicomkit.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mobicomkit.sample, PID: 31899
    java.lang.ClassCastException: com.mobicomkit.quickconversion.ConversionActivity cannot be cast to com.mobicomkit.uiwidgets.conversation.activity.MobiComActivity
            at com.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.deleteMessageFromDeviceList(MobiComConversationFragment.java:326)
            at com.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.onContextItemSelected(MobiComConversationFragment.java:897)
            at android.support.v4.app.Fragment.performContextItemSelected(Fragment.java:1909)
            at android.support.v4.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2058)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
            at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:4701)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
            at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
            at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
            at android.widget.AbsListView$3.run(AbsListView.java:3860)
            at android.os.Handler.handleCallback(Handler.java:739)
         

3. Single message delete not working in Messages (Activity based). Select any single message in the conversation list, select delete, nothing happens.

**Comment by devashishmamgain** [comment]
2. Delete single message is crashing app with the following error in case if the message is the last one in the list.
07-05 13:26:44.840  31899-31899/com.mobicomkit.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mobicomkit.sample, PID: 31899
    java.lang.ClassCastException: com.mobicomkit.quickconversion.ConversionActivity cannot be cast to com.mobicomkit.uiwidgets.conversation.activity.MobiComActivity
            at com.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.deleteMessageFromDeviceList(MobiComConversationFragment.java:326)
            at com.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.onContextItemSelected(MobiComConversationFragment.java:897)
            at android.support.v4.app.Fragment.performContextItemSelected(Fragment.java:1909)
            at android.support.v4.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2058)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
            at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:4701)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
            at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
            at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
            at android.widget.AbsListView$3.run(AbsListView.java:3860)
            at android.os.Handler.handleCallback(Handler.java:739)
         

3. Single message delete not working in Messages (Activity based). Select any single message in the conversation list, select delete, nothing happens.
