### ISSUE TITLE
BroadcastReceiver trying to return result during a non-ordered broadcast

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/mobi-com-kit#79]
07-17 12:25:25.449  15557-15598/com.mobicomkit.sample I/OpenGLRenderer﹕ Initialized EGL, version 1.4
07-17 12:25:25.471  15557-15598/com.mobicomkit.sample D/OpenGLRenderer﹕ Enabling debug mode 0
07-17 12:25:26.653  15557-15557/com.mobicomkit.sample I/GcmBroadcastReceiver﹕ Received notification: Bundle[mParcelledData.dataSize=100]
07-17 12:25:26.666  15557-15557/com.mobicomkit.sample E/BroadcastReceiver﹕ BroadcastReceiver trying to return result during a non-ordered broadcast
    java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast
            at android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:783)
            at android.content.BroadcastReceiver.setResultCode(BroadcastReceiver.java:549)
            at com.mobicomkit.sample.pushnotification.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:19)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609)
            at android.app.ActivityThread.access$1700(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-17 12:25:26.674  15557-15557/com.mobicomkit.sample I/MobiComPushReceiver﹕ Received notification: null

**Comment by a2zZuhaib** [comment]
Hi,
Dear developer of applozic i want to catch message in broadcast reciever and track the message is it Invitaion or not then forword it too UI.

I implement like this:
At user1 side i am sending message with metadata information which include flag via which i take a decision i have too show invitation dailog or forward to ui.

i dont know how to catch the message before show on ui..

**Comment by devashishmamgain** [comment]
hey @a2zZuhaib can you file a new issue for this?
