### ISSUE TITLE
java.lang.RuntimeException: Performing stop of activity that is not resumed:

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/mobi-com-kit#80]
07-17 14:24:33.293  19618-19618/com.mobicomkit.sample I/MTBroadcastReceiver﹕ Received broadcast, action: INSTRUCTION, message: null
07-17 14:24:33.689  19618-19618/com.mobicomkit.sample E/ActivityThread﹕ Performing stop of activity that is not resumed: {com.mobicomkit.sample/com.mobicomkit.sample.MainActivity}
    java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.mobicomkit.sample/com.mobicomkit.sample.MainActivity}
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3344)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.access$1100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by devashishmamgain** [comment]
Not able to reproduce, seems like issue with running the app multiple times from studio.
